---
name: Super-Linter

on:
  push:
    branches:
      - main # or your default branch

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use v3 or later for better performance and security

      - name: Run Super-Linter
        uses: github/super-linter@v4 # Use the latest version of Super-Linter
        env:
          DEFAULT_BRANCH: main # or your default branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Correct syntax for accessing secrets
